name: rocket_chat_dart
description: Similar to Rocket.Chat.Go.SDK and implement APIs according to the Rocket Chat document.
version: 0.0.39
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/rocket.chat.dart
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  enhanced_ddp:
    git:
      url: https://github.com/OwnWeb/enhanced_ddp.git
      ref: fixed
  crypto: ^2.1.5
  http: ^0.12.2
  http_parser: ^3.1.4
  mime: ^0.9.7
  json_annotation: ^3.1.1

dev_dependencies:
  test: ^1.15.7
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
